// rules sections
export const GETRULES = 'GETRULES';
export const GETRULESSUCCESS = 'GETRULESSUCCESS';
export const GETRULESFAILURE = 'GETRULESFAILURE';

export const UPDATERULE = 'UPDATERULE';
export const UPDATERULESUCCESS = 'UPDATERULESUCCESS';
export const UPDATERULEFAILURE= 'UPDATERULEFAILURE';

export const NEWRULE = 'NEWRULE';
export const NEWRULESUCCESS = 'NEWRULESUCCESS';
export const NEWRULEFAILURE = 'NEWRULEFAILURE';

export const UPDATESTATE = 'UPDATESTATE';
export const EDITRULE = 'EDITRULE';
