function measurementList(){
  return [{value: 'Bag', label: 'BG'},
	{value: 'Barrel', label: 'BA'},
	{value: 'Bolt', label: 'BT'},
	{value: 'Box', label: 'BOX'},
	{value: 'Bunch', label: 'BH'},
	{value: 'Bundle', label: 'BE'},
	{value: 'Butt', label: 'BU'},
	{value: 'Canister', label: 'CI'},
	{value: 'Carton', label: 'CT'},
	{value: 'Case', label: 'CS'},
	{value: 'Centimeter', label: 'CM'},
	{value: 'Container', label: 'CON'},
	{value: 'Crate', label: 'CR'},
	{value: 'Cylinder', label: 'CY'},
	{value: 'Dozen', label: 'DOZ'},
	{value: 'Foot', label: 'FT'},
	{value: 'Kilogram', label: 'KG'},
	{value: 'Kilograms', label: 'KGS'},
	{value: 'Liter', label: 'L'},
	{value: 'Meter', label: 'M'},
	{value: 'Pakage', label: 'PK'},
	{value: 'Packet', label: 'PA'},
	{value: 'Pair', label: 'PAR'},
	{value: 'Pairs', label: 'PRS'},
	{value: 'Pallet', label: 'PAL'},
	{value: 'Piece', label: 'PC'},
	{value: 'Pieces', label: 'PCS'},
	{value: 'Pound', label: 'LB'},
	{value: 'Proof Liter', label: 'PF'},
	{value: 'Roll', label: 'ROL'},
	{value: 'Set', label: 'SET'},
	{value: 'Square Meter', label: 'SME'},
	{value: 'Square Yard', label: 'SYD'},
	{value: 'Tube', label: 'TU'},
	{value: 'Yard', label: 'YD'}];
};

exports.measurementList = measurementList;